#!/bin/bash
printf '%o\n' $(( $(echo $WATER | tr 'water' '01234' | python3 -c "import sys
print(int(sys.stdin.read().strip(),5))") + $(echo $STIR | tr 'stir.' '01234' | python3 -c "import sys
print(int(sys.stdin.read().strip(),5))") )) | tr '01234567' 'bestchol'
