#!/bin/bash
printf '%o\n' $(( $(echo $WATER | tr 'water' '01234' | python3 -c "import sys; s=sys.stdin.read().strip(); print(int(s,5))") + $(echo $STIR | tr 'stir.' '01234' | python3 -c "import sys; s=sys.stdin.read().strip(); print(int(s,5))") )) | tr '01234567' 'bestchol'
